package com.sunflow.engine.eventsystem.events;

public enum EventType {
	KEY_INPUT, KEY_PRESS, KEY_RELEASE, KEY_REPEAT,

	MOUSE_INPUT, MOUSE_PRESS, MOUSE_RELEASE,
	MOUSE_MOTION, MOUSE_MOVE, MOUSE_DRAG,
	MOUSE_ONSCREEN, MOUSE_ENTER, MOUSE_EXIT,

	SCROLL,

	WINDOW_RESIZE, WINDOW_MOVE,

//	JOYSTICK
	;
}
