package com.sunflow.engine.eventsystem.events;

import static org.lwjgl.glfw.GLFW.*;

import org.lwjgl.glfw.GLFW;

public interface EventConstants {

	int
	/*   */ PRESS = GLFW.GLFW_PRESS,
			RELEASE = GLFW.GLFW_RELEASE,
			REPEAT = GLFW.GLFW_REPEAT,
			KEY_LAST = GLFW.GLFW_KEY_LAST,
			MOUSE_BUTTON_LAST = GLFW.GLFW_MOUSE_BUTTON_LAST,
			JOYSTICK_LAST = GLFW.GLFW_JOYSTICK_LAST,
			GAMEPAD_AXIS_LAST = GLFW.GLFW_GAMEPAD_AXIS_LAST,
			GAMEPAD_BUTTON_LAST = GLFW.GLFW_GAMEPAD_BUTTON_LAST;

	// Buttons
	int
	/*   */ MOUSE_BUTTON_LEFT = GLFW_MOUSE_BUTTON_LEFT,
			MOUSE_BUTTON_RIGHT = GLFW_MOUSE_BUTTON_RIGHT,
			MOUSE_BUTTON_MIDDLE = GLFW_MOUSE_BUTTON_MIDDLE;

	// Keys
	int
	/*   */ W = GLFW_KEY_W,
			A = GLFW_KEY_A,
			S = GLFW_KEY_S,
			D = GLFW_KEY_D,

			Q = GLFW_KEY_Q,
			E = GLFW_KEY_E,
			R = GLFW_KEY_R,
			F = GLFW_KEY_F,

			UP = GLFW_KEY_UP,
			LEFT = GLFW_KEY_LEFT,
			RIGHT = GLFW_KEY_RIGHT,
			DOWN = GLFW_KEY_DOWN,

			SPACE = GLFW_KEY_SPACE,
			ESCAPE = GLFW_KEY_ESCAPE,
			ENTER = GLFW_KEY_ENTER,
			SHIFT = GLFW_KEY_LEFT_SHIFT,
			SHIFT_RIGHT = GLFW_KEY_RIGHT_SHIFT,
			CONTROL = GLFW_KEY_LEFT_CONTROL,
			CONTROL_RIGHT = GLFW_KEY_RIGHT_CONTROL,
			ALT = GLFW_KEY_LEFT_ALT,
			ALT_RIGHT = GLFW_KEY_RIGHT_ALT,

			F1 = GLFW_KEY_F1,
			F2 = GLFW_KEY_F2,
			F3 = GLFW_KEY_F3,
			F4 = GLFW_KEY_F4,
			F5 = GLFW_KEY_F5,
			F6 = GLFW_KEY_F6,
			F7 = GLFW_KEY_F7,
			F8 = GLFW_KEY_F8,
			F9 = GLFW_KEY_F9,
			F10 = GLFW_KEY_F10,
			F11 = GLFW_KEY_F11,
			F12 = GLFW_KEY_F12;
}
